### ISSUE TITLE
Game Design Document Template

### ISSUE THREAD

**Issue by bustinjurkz** [Evan-HR/HandBurglars#3]
Hello Dr. Smith, 
Below is a sample game design doc we found.  Essentially, it appears to be a "living document" - to be updated as it goes.  We will fill in what we can for our first sprint (done by Oct 1st).  The only section I don't see as important are some stuff in Section X, but let us know if this is a good starter template to follow.  We will add in diagrams in things like the character design, levels, etc., as well as use openleaf for collaborative LaTeX.  Please close the issue if you feel this is a decent template, or if you have any suggestions to add/remove.  Thanks!
[BaldwinGameDesignDocumentTemplate.pdf](https://github.com/Evan-HR/HandBurglars/files/2412556/BaldwinGameDesignDocumentTemplate.pdf)

**Comment by smiths** [comment]
The proposed template looks very thorough.  Seems like a good idea to me.  You are right that you don't need all of section 10 (you don't really have a budget), but you should keep it.  You can always leave sections blank.

Instead of overleaf, you should think about just putting your tex files under version control in GitHub.  You should set up the project as you see fit, but using GitHub for LaTeX has worked successfully on many projects.
